name: generate-pr-patch
description:
  Collect failing CI context, call TensorZero, and emit untrusted patch/comment
  artifacts for later processing.
author: shuyangli

branding:
  icon: alert-circle
  color: orange

inputs:
  tensorzero-base-url:
    description: Base URL for the TensorZero instance.
    required: true
  tensorzero-diff-patched-successfully-metric-name:
    description: Metric name for tracking diff patching success.
    required: true
  output-artifacts-dir:
    description:
      Directory where untrusted artifacts (manifest, diff, comments, logs) will
      be written for upload.

runs:
  using: node24
  main: ../dist/generate-pr-patch/index.js
