name: generate-pr-patch
description:
  Download failed workflow artifacts, emit their contents, and prepare for
  automated diagnosis.
author: shuyangli

branding:
  icon: alert-circle
  color: orange

inputs:
  token:
    description: GitHub token used to query workflow run artifacts.
    required: true
  mode:
    description: |
      Operation mode: "patch-only" generates patch without creating PR,
      "full" (default) creates PR directly.
    default: 'full'
  tensorzero-base-url:
    description: Base URL for the TensorZero instance.
    required: true
  tensorzero-diff-patched-successfully-metric-name:
    description: Metric name for tracking diff patching success.
    required: true
  clickhouse-url:
    description:
      URL for ClickHouse HTTP interface, in the format of
      http[s]://[username:password@]hostname:port[/database].
    required: true
  clickhouse-table:
    description: Table where inference to PR associations should be recorded.
    required: true
  output-artifacts-dir:
    description:
      Directory to store output artifacts (e.g. LLM prompt and output, git diff)
      for debugging purposes, if present.

outputs:
  has-changes:
    description: 'Whether the agent made any changes (true/false)'
  patch-file:
    description: 'Path to the generated patch file (only in patch-only mode)'
  metadata-file:
    description: 'Path to the metadata JSON file (only in patch-only mode)'

runs:
  using: node24
  main: ../dist/generate-pr-patch/index.js
