name: apply-pr-artifacts
description:
  Consume TensorZero CI Bot artifacts, verify them, and apply patches and
  comments with privileged GitHub access.
author: shuyangli

inputs:
  token:
    description: GitHub token with contents/pull-request write access.
    required: true
  artifact-directory:
    description: Directory containing the downloaded artifact bundle.
    required: true
  manifest-path:
    description:
      Relative path to the manifest inside the artifact directory (defaults to
      manifest.json).
    required: false
  tensorzero-base-url:
    description: Base URL for the TensorZero instance.
    required: true
  tensorzero-diff-patched-successfully-metric-name:
    description: Metric name for tracking diff patching success.
    required: true
  clickhouse-url:
    description:
      URL for ClickHouse HTTP interface, in the format of
      http[s]://[username:password@]hostname:port[/database].
    required: true
  clickhouse-table:
    description: Table where inference to PR associations should be recorded.
    required: true

runs:
  using: node24
  main: ../dist/apply-pr-artifacts/index.js
